### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by hazcod** [ribtoks/tdg-github-action#1]
Hi, receiving this from runs:
```
Current runner version: '2.272.0'
2
Operating System
6
Virtual Environment
10
Prepare workflow directory
11
Prepare all required actions
12
Download action repository 'actions/checkout@v2.3.1'
13
Download action repository 'ribtoks/tdg-github-action@master'
14
##[error]ribtoks/tdg-github-action/master/action.yml (Line: 54, Col: 9): Unexpected value ''
15
##[error]ribtoks/tdg-github-action/master/action.yml (Line: 54, Col: 9): Unexpected value ''
16
##[error]System.ArgumentException: Unexpected type 'NullToken' encountered while reading 'outputs'. The type 'MappingToken' was expected.
17
   at GitHub.DistributedTask.ObjectTemplating.Tokens.TemplateTokenExtensions.AssertMapping(TemplateToken value, String objectDescription)
18
   at GitHub.Runner.Worker.ActionManifestManager.Load(IExecutionContext executionContext, String manifestFile)
19
##[error]Fail to load ribtoks/tdg-github-action/master/action.yml
```

**Comment by ribtoks** [comment]
Hi @hazcod 

Thanks for reporting this issue. I fixed it in master.
